version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: truvest_identity_management
        POSTGRES_USER: dbadmin
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
  truvest-identity-management:
      restart: always
      build:
        dockerfile: Dockerfile
        context: .
      environment:
        # Postgres Details
        DB_HOST: postgres
        DB_DRIVER: postgres
        DB_USER: dbadmin
        DB_PASSWORD: password
        DB_NAME: truvest_identity_management
        DB_PORT: 5432
        # APP details
        APP_PROTOCOL: http
        APP_HOST: localhost
        APP_PORT: 9191
        # GORM Configuration
        GORM_AUTOMIGRATE: "true"
        # SMTP Details
        SMTP_HOST: smtp.gmail.com
        SMTP_PORT: 587
        # System Configuration Details
        API_SECRET: 9c5b761a9bf8f74da84c57101669b8042b860ca5871a15c4e729758ad1dee58d562ddf8fa303ada1f3e0278fdff4af9a72f57ce0514be98f6a959daabda926f5
        SYSTEM_EMAIL: system@gmail.com
        SYSTEM_EMAIL_PASSWORD: change_me
        SYSTEM_ADMIN_USERNAME: admin
        SYSTEM_ADMIN_FIRSTNAME: admin
        SYSTEM_ADMIN_LASTNAME: user
        SYSTEM_ADMIN_PASSWORD: password
        ALLOWED_ORIGINS: "*"
        # JWT Token Settings
        ACCESS_TOKEN_EXPIRY_IN_MILLISECOND: 3600000 # 1 hour
        # OAuth Provider Options
        GOOGLE_KEY: change_me
        GOOGLE_SECRET: change_me
        GITHUB_KEY: change_me
        GITHUB_SECRET: change_me
      ports:
        - 9191:9191
      depends_on:
        - postgres